### ISSUE TITLE
    print(style + msg, end = "")                            ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by littleheary** [lilloX/routerPWN#1]
Traceback (most recent call last):
  File "routerPwn.py", line 2, in <module>
    import classes
  File "/soft/network/routerPWN/classes.py", line 3, in <module>
    import aux
  File "/soft/network/routerPWN/aux.py", line 29
    print(style + msg, end = "")
                           ^
SyntaxError: invalid syntax

**Comment by lilloX** [comment]
Hi, You are using python 2.X
As you can see on the Readme file, you need to use python 3.
Thanks
